version: "3.9"

volumes:
  db-data-master-1:
    name: socialnetwork-db-master-1
  grafana-data:
    name: socialnetwork-grafana-data
  prometheus-data:
    name: socialnetwork-prometheus-data

services:
  socialnetwork-api-1:
    build:
      context: ./src
      dockerfile: SocialNetworkApi/Dockerfile
    container_name: socialnetwork-api-1
    depends_on:
      - socialnetwork-db-master
    environment:
      - HTTP_PORT=8080
      - DatabaseSettings__MasterConnectionString=Server=socialnetwork-db-master;Port=5432;Database=socialnetwork;User ID=postgres_user;Password=!QAZ2wsx;No Reset On Close=true; Include Error Detail=true
      - DatabaseSettings__ReplicaConnectionStrings__0=Server=socialnetwork-db-master;Port=5432;Database=socialnetwork;User ID=postgres_user;Password=!QAZ2wsx;No Reset On Close=true; Include Error Detail=true
      - DatabaseSettings__ReplicaConnectionStrings__1=Server=socialnetwork-db-master;Port=5432;Database=socialnetwork;User ID=postgres_user;Password=!QAZ2wsx;No Reset On Close=true; Include Error Detail=true
      - Jwt__Key=vsjq3w7QS+5deEzxVBrEGTwUC58tgxt9FVK3QUYR6pM=
      - Jwt__Issuer=socialnetwork.com
      - Jwt__Audience=socialnetwork.com
      - Serilog__Using__0=Serilog.Sinks.Console
      - Serilog__MinimumLevel=Debug
      - Serilog__WriteTo__0__Name=Console   
    ports:
      - "5001:8080"
    networks:
      - sn-network

  socialnetwork-dbmigrator-1:
    build:
      context: ./src
      dockerfile: SocialNetwork.DbMigrator/Dockerfile
    container_name: socialnetwork-dbmigrator-1
    depends_on:
      - socialnetwork-db-master
    environment:
      - RUN_OPTIONS=migrateUp
      - DatabaseSettings__MasterConnectionString=Server=socialnetwork-db-master;Port=5432;Database=socialnetwork;User ID=postgres_user;Password=!QAZ2wsx;No Reset On Close=true; Include Error Detail=true
      - Serilog__Using__0=Serilog.Sinks.Console
      - Serilog__MinimumLevel=Debug
      - Serilog__WriteTo__0__Name=Console
    ports:
      - "5002:8080"
    networks:
      - sn-network

  socialnetwork-db-master:
    image: postgres:latest
    container_name: socialnetwork-db-master
    user: "postgres"
    environment:
      POSTGRES_DB: socialnetwork
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: "!QAZ2wsx"
      #PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data-master-1:/var/lib/postgresql/data
      #- ./init-master.sh:/docker-entrypoint-initdb.d/init-master.sh
    ports:
      - "5400:5432"
    networks:
      - sn-network

  # exporter for docker container metrics
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - sn-network

  # exporter for db metrics
  exporter-postgres-master:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: exporter-postgres-master
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres_user:!QAZ2wsx@socialnetwork-db-master:5432/socialnetwork?sslmode=disable"
      #POSTGRES_EXPORTER_EXTEND_QUERY_PATH: "/docker-config/postgres-exporter-queries.yml"
    ports:
      - "9190:9187"
    volumes:
      #- ./docker-config/postgres-exporter-queries.yml:/docker-config/postgres-exporter-queries.yml
      - ./docker-config/postgres_exporter.yml:/postgres_exporter.yml
    depends_on:
      - socialnetwork-db-master
    networks:
      - sn-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./docker-config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - cadvisor
      - exporter-postgres-master
    networks:
      - sn-network
     
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=!QAZ2wsx
    ports:
      - "3000:3000"      
    networks:
      - sn-network

networks:
  sn-network:
    driver: bridge