version: "3.9"

volumes:
  socialnetwork-db-1:
    name: socialnetwork-db-1
  influxdb-data:
  grafana-data:    

services:
  socialnetwork-1:
    build:
      context: ./src
      dockerfile: SocialNetworkApi/Dockerfile
    container_name: socialnetwork-1
    depends_on:
      - socialnetwork-db-1
    environment:
      - HTTP_PORT=8080
      - DatabaseSettings__ConnectionString=Server=socialnetwork-db-1;Port=5432;Database=socialnetwork;User ID=test;Password=test;No Reset On Close=true; Include Error Detail=true
      - Jwt__Key=vsjq3w7QS+5deEzxVBrEGTwUC58tgxt9FVK3QUYR6pM=
      - Jwt__Issuer=socialnetwork.com
      - Jwt__Audience=socialnetwork.com
      - Serilog__Using__0=Serilog.Sinks.Console
      - Serilog__MinimumLevel=Debug
      - Serilog__WriteTo__0__Name=Console   
    ports:
      - "5001:8080"
    networks:
      - custom-network

  socialnetwork-dbmigrator-1:
    build:
      context: ./src
      dockerfile: SocialNetworkApi/Dockerfile
    container_name: socialnetwork-dbmigrator-1
    depends_on:
      - socialnetwork-db-1
    environment:
      - HTTP_PORT=8080
      - RUN_OPTIONS=migrateUp
      - DatabaseSettings__ConnectionString=Server=socialnetwork-db-1;Port=5432;Database=socialnetwork;User ID=test;Password=test;No Reset On Close=true; Include Error Detail=true
      - Jwt__Key=vsjq3w7QS+5deEzxVBrEGTwUC58tgxt9FVK3QUYR6pM=
      - Jwt__Issuer=socialnetwork.com
      - Jwt__Audience=socialnetwork.com
      - Serilog__Using__0=Serilog.Sinks.Console
      - Serilog__MinimumLevel=Debug
      - Serilog__WriteTo__0__Name=Console
    ports:
      - "5002:8080"
    networks:
      - custom-network

  socialnetwork-db-1:
    image: postgres:latest
    container_name: socialnetwork-db-1
    environment:
      - POSTGRES_DB=socialnetwork
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5401:5432"
    volumes:
      - socialnetwork-db-1:/var/lib/postgresql/data
    networks:
      - custom-network
      
  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=LoadTestDb
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
#      - INFLUXDB_ORGANIZATION_NAME=socialnetwork - setup in ui
#      - INFLUXDB_BUCKET_NAME=loadtest - setup in ui
    ports:
      - "8086:8086"
    networks:
      - custom-network
      
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
    ports:
      - "3000:3000"      
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge