global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'postgres'
    scrape_interval: 5s
    static_configs:
      - targets: ['postgres-exporter:9187']

#  - job_name: 'socialnetwork'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['socialnetwork-1:8080'] 