global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'postgres-master'
    scrape_interval: 5s
    static_configs:
      - targets: ['exporter-postgres-master:9190']


#          - 'postgres-exporter-replica-1:9191'
#          - 'postgres-exporter-replica-2:9192'

#  - job_name: 'postgres-replica-1'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['postgres-exporter-replica-1:9191']
#
#  - job_name: 'postgres-replica-2'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['postgres-exporter-replica-2:9192']
        
#  - job_name: 'socialnetwork'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['socialnetwork-1:8080'] 