{
 "title": "SocialNetwork Db Master PgMonitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Общая статистика по базам данных",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_database_xact_commit{datname=\"socialnetwork\", instance=\"exporter-postgres-master:9187\"}",
     "legendFormat": "Количество транзакций"
    },
    {
     "expr": "pg_stat_database_blks_read{datname=\"socialnetwork\", instance=\"exporter-postgres-master:9187\"}",
     "legendFormat": "Количество операций чтения"
    }
   ]
  },
  {
   "title": "Индексные и последовательные сканы по таблицам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_seq_scan{datname=\"socialnetwork\", relname=\"users\", instance=\"exporter-postgres-master:9187\"}",
     "legendFormat": "tables_seq_{{relname}}"
    },
    {
     "expr": "pg_stat_user_tables_idx_scan{datname=\"socialnetwork\", relname=\"users\", instance=\"exporter-postgres-master:9187\"}",
     "legendFormat": "tables_idx_{{relname}}"
    }
   ]
  },
  {
   "title": "Информация о блокировках",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_locks_count{datname=\"socialnetwork\", instance=\"exporter-postgres-master:9187\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Размер базы данных",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"socialnetwork\", instance=\"exporter-postgres-master:9187\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Текущее количество активных соединений",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"socialnetwork\", state=\"active\", instance=\"exporter-postgres-master:9187\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Статистика репликации",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "pg_stat_replication_reply_time", "legendFormat": "slot_name_{{slot_name}}" },
    {
     "expr": "pg_replication_lag_seconds",
     "legendFormat": "Состояние репликации {{instance}}"
    },
    { "expr": "pg_replication_lag_seconds", "legendFormat": "lag_{{job}}" }
   ]
  },
  {
   "title": "Максимальная длительность транзакций",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{datname=\"socialnetwork\", instance=\"exporter-postgres-master:9187\",state=\"active\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Размер табличного пространства",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "pg_stat_database_conflicts_confl_tablespace{datname=\"socialnetwork\", server=\"socialnetwork-db-master:5432\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}