{
 "title": "SocialNetwork Db Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "IO usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{job=\"cadvisor\", name=~\"^socialnetwork-db.*\"}",
     "legendFormat": "usage_{{name}}"
    }
   ]
  },
  {
   "title": "IO read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "container_fs_reads_total{job=\"cadvisor\", name=~\"^socialnetwork-db.*\"}",
     "legendFormat": "read_{{name}}"
    }
   ]
  },
  {
   "title": "IO write",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "container_fs_writes_total{job=\"cadvisor\", name=~\"^socialnetwork-db.*\"}",
     "legendFormat": "write_{{name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(cpu, name) (container_cpu_usage_seconds_total{job=\"cadvisor\", name=~\"^socialnetwork-db.*\"})",
     "legendFormat": "{{name}}_{{cpu}}"
    },
    {
     "expr": "sum by (name) (container_cpu_usage_seconds_total{job=\"cadvisor\", name=~\"^socialnetwork-db.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{job=\"cadvisor\", name=~\"^socialnetwork-db.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "File System inodes Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "container_fs_inodes_total{job=\"cadvisor\", name=~\"^socialnetwork-db.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network recieve",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{job=\"cadvisor\", name=~\"^socialnetwork-db.*\"}",
     "legendFormat": "{{name}}_{{interface}}"
    }
   ]
  },
  {
   "title": "Network transmit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{job=\"cadvisor\", name=~\"^socialnetwork-db.*\"}",
     "legendFormat": "{{name}}_{{interface}}"
    }
   ]
  },
  {
   "title": "File System inodes Free",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "container_fs_inodes_free{job=\"cadvisor\", name=~\"^socialnetwork-db.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}