{
 "title": "SocialNetwork Db PgMonitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Информация о блокировках master",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_locks_count{datname=\"socialnetwork\", job=\"postgres-master\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Информация о блокировках replica1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "pg_locks_count{datname=\"socialnetwork\", job=\"postgres-replica-1\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Информация о блокировках replica2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "pg_locks_count{datname=\"socialnetwork\", job=\"postgres-replica-2\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Статистика репликации",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    { "expr": "pg_stat_replication_reply_time", "legendFormat": "{{job}}_{{slot_name}}" }
   ]
  },
  {
   "title": "Статистика репликации",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    { "expr": "pg_replication_lag_seconds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Размер базы данных",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"socialnetwork\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Последовательные сканы по таблицам",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_seq_scan{relname=\"users\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Индексные сканы по таблицам",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_idx_scan{relname=\"users\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Максимальная длительность транзакций",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration{datname=\"socialnetwork\", state=\"active\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Количество транзакций",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by (job) (rate(pg_stat_database_xact_commit[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество операций чтения",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "pg_stat_database_blks_read{datname=\"socialnetwork\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Текущее количество активных соединений",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"socialnetwork\", state=\"active\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}