# slave/Dockerfile
FROM postgres:latest

# Copy the entrypoint script
COPY hw3.replica_entrypoint.sh /usr/local/bin/hw3.replica_entrypoint.sh

# Ensure the entrypoint script is executable
RUN chmod +x /usr/local/bin/hw3.replica_entrypoint.sh

# Switch to the postgres user
# USER postgres_user
USER postgres

# Set entrypoint to execute the script before starting PostgreSQL
# ENTRYPOINT ["echo", "Testing entrypoint script"]
ENTRYPOINT ["/usr/local/bin/hw3.replica_entrypoint.sh"]
CMD ["postgres"]