{
 "title": "DbMaster Container",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"socialnetwork-db-1\"}[$__rate_interval])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"socialnetwork-db-1\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=\"socialnetwork-db-1\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "container_fs_io_time_seconds_total{name=\"socialnetwork-db-1\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "DB stat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"socialnetwork\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "container_tasks_state{state=\"running\", container_label_com_docker_compose_service=\"socialnetwork-db-1\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Информация о блокировках",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "pg_locks_count{datname=\"socialnetwork\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Индексные и последовательные сканы по таблицам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_seq_scan{datname=\"socialnetwork\", relname=\"users\"}",
     "legendFormat": "{{datname}}_seq_scan"
    },
    {
     "expr": "pg_stat_user_tables_idx_scan{datname=\"socialnetwork\", relname=\"users\"}",
     "legendFormat": "{{datname}}_index"
    }
   ]
  },
  {
   "title": "Размер базы данных",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"socialnetwork\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "container_fs_io_time_seconds_total{name=\"socialnetwork-1\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Статистика фонового записывающего процесса",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "pg_stat_bgwriter_buffers_checkpoint{datname=\"socialnetwork\"}",
     "legendFormat": "Сбросы страниц"
    },
    {
     "expr": "pg_stat_bgwriter_buffers_clean{datname=\"socialnetwork\"}",
     "legendFormat": "Очистки страниц"
    }
   ]
  },
  {
   "title": "Общая статистика по базам данных",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "pg_stat_database_xact_commit{datname=\"socialnetwork\"}",
     "legendFormat": "Количество транзакций"
    },
    {
     "expr": "pg_stat_database_blks_read{datname=\"socialnetwork\"}",
     "legendFormat": "Количество операций чтения"
    }
   ]
  },
  {
   "title": "Размер табличного пространства",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "pg_tablespace_size_bytes{datname=\"socialnetwork\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Статистика репликации",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "pg_stat_replication_delay_bytes{datname=\"socialnetwork\"}",
     "legendFormat": "Задержка репликации в байтах"
    },
    {
     "expr": "pg_stat_replication_state{datname=\"socialnetwork\"}",
     "legendFormat": "Состояние репликации"
    }
   ]
  },
  {
   "title": "Максимальная длительность транзакций",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration_seconds{datname=\"socialnetwork\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}