{
 "title": "SocialNetwork Api Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "File System inodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_fs_inodes_total{name=\"socialnetwork-api-1\", job=\"cadvisor\"}",
     "legendFormat": "total_{{name}}"
    },
    {
     "expr": "container_fs_inodes_free{name=\"socialnetwork-api-1\", job=\"cadvisor\"}",
     "legendFormat": "free_{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"socialnetwork-api-1\", job=\"cadvisor\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "group by(cpu) (container_cpu_usage_seconds_total{name=\"socialnetwork-api-1\", job=\"cadvisor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{name=\"socialnetwork-api-1\", job=\"cadvisor\"}",
     "legendFormat": "receive_{{interface}}"
    },
    {
     "expr": "container_network_transmit_bytes_total{name=\"socialnetwork-api-1\", job=\"cadvisor\"}",
     "legendFormat": "transmit_{{interface}}"
    }
   ]
  },
  {
   "title": "IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=\"socialnetwork-api-1\", job=\"cadvisor\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "container_fs_reads_total{name=\"socialnetwork-api-1\", job=\"cadvisor\"}",
     "legendFormat": "read"
    },
    {
     "expr": "container_fs_writes_total{name=\"socialnetwork-api-1\", job=\"cadvisor\"}",
     "legendFormat": "write"
    }
   ]
  }
 ]
}