{
 "title": "SocialNetwork Db Master",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Общая статистика по базам данных",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_database_xact_commit{datname=\"socialnetwork\"}",
     "legendFormat": "Количество транзакций"
    },
    {
     "expr": "pg_stat_database_blks_read{datname=\"socialnetwork\"}",
     "legendFormat": "Количество операций чтения"
    }
   ]
  },
  {
   "title": "Индексные и последовательные сканы по таблицам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_user_tables_seq_scan{datname=\"socialnetwork\", relname=\"users\"}",
     "legendFormat": "tables_seq_{{relname}}"
    },
    {
     "expr": "pg_stat_user_tables_idx_scan{datname=\"socialnetwork\", relname=\"users\"}",
     "legendFormat": "tables_idx_{{relname}}"
    }
   ]
  },
  {
   "title": "Информация о блокировках",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_locks_count{datname=\"socialnetwork\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Размер базы данных",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"socialnetwork\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Текущее количество активных соединений",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"socialnetwork\", state=\"active\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Статистика репликации",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pg_stat_replication_delay_bytes{datname=\"socialnetwork\"}",
     "legendFormat": "Задержка репликации в байтах"
    },
    {
     "expr": "pg_stat_replication_state{datname=\"socialnetwork\"}",
     "legendFormat": "Состояние репликации"
    }
   ]
  },
  {
   "title": "Максимальная длительность транзакций",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration_seconds{datname=\"socialnetwork\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Размер табличного пространства",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "pg_tablespace_size_bytes{datname=\"socialnetwork\", tablespacename=\"users\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}